### ISSUE TITLE
VisualsBulkDownloadTool powershell script errors

### ISSUE THREAD

**Issue by Laurandaz** [SteveWinward/PowerBI#1]
Hello Steve,

This seems like a great tool! I am attempting to run this powershell script in cmd window, getting unexpected token and missing argument in parameter list. Any help is appreciated!!
![cmd window ps1 errors](https://user-images.githubusercontent.com/35981075/58219754-04fe4c00-7cda-11e9-9137-92ac501d2e96.PNG)

Thank you,
Laura

**Comment by SteveWinward** [comment]
Hey Laura.

So I would recommend to use the PowerShell console instead of the Command Prompt if you can.  However, if you want to use the Command Prompt then this command should work,

    PowerShell.exe -File VisualsBulkDownloadTool.ps1

Also, if you wanted to use the command line switches I have in the PowerShell script you could that with this command below,

    PowerShell.exe -Command .\VisualsBulkDownloadTool.ps1 -CertifiedOnly -MicrosoftOnly

If this works for you let me know and I will close this issue.

**Comment by Laurandaz** [comment]
Hi Steve, Thank you for the feedback and guidance for PS. I was able to get it to run but see the same errors (unexpected token and missing argument in parameter list).
![PS ps1 errors](https://user-images.githubusercontent.com/35981075/58521764-8ac34100-818b-11e9-8b11-4270971d444b.PNG)

**Comment by SteveWinward** [comment]
Hey Laura,

How are you downloading the VisualsBulkDownloadTool.ps1 script?  One of the error messages you are getting is referring to an unexpected token which is the url of the script hosted in GitHub which is odd.

Can you try this?

1. Download the repo as a zip file 
a. Go here, https://github.com/SteveWinward/PowerBI
b. Clone or download > Download Zip
2. Extract the zip file
3. Open up a PowerShell console and naviaget to the Misc folder (PowerBI-master\PowerBI-master\Misc)
4. Run the script ```.\VisualsBulkDownloadTool.ps1```

**Comment by Laurandaz** [comment]
Hi Steve,
This looks different from what I had before and it is working! I can close
out the issue. Thanks a ton for your help!
Laura

[image: image.png]

**Comment by Laurandaz** [comment]
Hi Steve,

Thank you for troubleshooting with me. I spoke too soon! After a closer
look I am seeing a SSL/TLS secure channel creation error.
[image: PS ssl tls ps1 errors.PNG]

**Comment by SteveWinward** [comment]
Hey Laura.  I think you forgot to attach the screenshot.  For some reason its not showing up like the other ones you added.

**Comment by Laurandaz** [comment]
![PS ssl tls ps1 errors](https://user-images.githubusercontent.com/35981075/58603775-fb3b9200-825f-11e9-8a5e-0483a565f037.PNG)

**Comment by SteveWinward** [comment]
This is odd.  Do you see this error on the same visual, or does it seem to happen to random visuals when you see the error?

**Comment by SteveWinward** [comment]
I updated the script to use retry logic to download each visual.  This will hopefully prevent transient download errors.  Can you try downloading the updated version of the script and try it again?

**Comment by Laurandaz** [comment]
I downloaded the updated version still SSL/TLS secure channel errors ![PS ssl tls ps1 errors2](https://user-images.githubusercontent.com/35981075/58675102-d0fdd900-8320-11e9-8635-b4abdfd1afea.PNG)

**Comment by SteveWinward** [comment]
What version of Windows are you running?  Also, can you run this in a PowerShell console to determine what version of the PowerShell console you are running?

    $PSVersionTable.PSVersion

Lastly, based off of this StackOverflow [post](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel) I updated the script to force all web requests to use TLS 1.2.  Can you try the updated version of the script I just pushed?

**Comment by Laurandaz** [comment]
Windows 8. Checking the post...
![PS version](https://user-images.githubusercontent.com/35981075/58676748-5e442c00-8327-11e9-8a78-3f54008b3257.PNG)

**Comment by SteveWinward** [comment]
Let me know if the update I made to the script fixes the issue.  If not, I would need to troubleshoot this script on a Windows 8 OS which might take me a while to get setup.

**Comment by Laurandaz** [comment]
![PS download working](https://user-images.githubusercontent.com/35981075/58704908-8f4e4c00-837b-11e9-88c7-9accfaca360b.PNG)

Success Yaay!

**Comment by Laurandaz** [comment]
My colleagues will be very happy, Thank You! Now I need to get the files onto our network. :+1:

**Comment by SteveWinward** [comment]
Excellent!  I'm glad to hear its working now, I'm closing the issue now!
